# Generated by Django 5.0 on 2023-12-08 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
